### ISSUE TITLE
Differences between 4m6 and 4m15

### ISSUE THREAD

**Issue by sabatale** [YasogaN/google-maps-review-scraper#15]
Where do you suggest to find the properly formatted URLs?

For example, both are valid but only the second one will be parsed properly:

[https://www.google.com/maps/place/Palace+of+Versailles/@48.8039211,2.0779952,13z/data=!3m1!5s0x47e67dbeb2a2d1cb:0xfaa83490b67c0c36!4m15!1m8!3m7!1s0x47e67db475f420bd:0x869e00ad0d844aba!2s78000+Versailles,+France!3b1!8m2!3d48.8022585!4d2.1297422!16zL20vMDgwZzM!3m5!1s0x47e67d94d7b14c75:0x538fcc15f59ce8f!8m2!3d48.8048649!4d2.1203554!16zL20vMGRfNjE](https://www.google.com/maps/place/Palace+of+Versailles/@48.8039211,2.0779952,13z/data=!3m1!5s0x47e67dbeb2a2d1cb:0xfaa83490b67c0c36!4m15!1m8!3m7!1s0x47e67db475f420bd:0x869e00ad0d844aba!2s78000+Versailles,+France!3b1!8m2!3d48.8022585!4d2.1297422!16zL20vMDgwZzM!3m5!1s0x47e67d94d7b14c75:0x538fcc15f59ce8f!8m2!3d48.8048649!4d2.1203554!16zL20vMGRfNjE)

[https://www.google.com/maps/place/Palace+of+Versailles/@48.8039211,2.0779952,13z/data=!3m1!5s0x47e67dbeb2a2d1cb:0xfaa83490b67c0c36!4m6!3m5!1s0x47e67d94d7b14c75:0x538fcc15f59ce8f!8m2!3d48.8048649!4d2.1203554!16zL20vMGRfNjE](https://www.google.com/maps/place/Palace+of+Versailles/@48.8039211,2.0779952,13z/data=!3m1!5s0x47e67dbeb2a2d1cb:0xfaa83490b67c0c36!4m6!3m5!1s0x47e67d94d7b14c75:0x538fcc15f59ce8f!8m2!3d48.8048649!4d2.1203554!16zL20vMGRfNjE)

The difference being `4m15!1m8!3m7!1s0x47e67db475f420bd:0x869e00ad0d844aba!2s78000+Versailles,+France!3b1!8m2!3d48.8022585!4d2.1297422!16zL20vMDgwZzM`. Is there a way to reformat it properly?

**Comment by sabatale** [comment]
Closing this.

`url.match(/!1s([a-zA-Z0-9_:]+)!/)` does not catch the right Place ID when the URL has multiple "1s" parameters.

**Comment by YasogaN** [comment]
Hi @sabatale
Apologies for the late reply! I encountered this issue during testing as well. It seems to be a quirk with Google Maps, where the URL retains the last place searched or visited, leading to inconsistencies in the parameters.

I’ll look into this further, and a proper fix will be addressed in version 1.4. Thanks for pointing this out, and I appreciate your patience!

Let me know if you face any other issues in the meantime.
