### ISSUE TITLE
How do I run this ?

### ISSUE THREAD

**Issue by Bharat0112** [YasogaN/google-maps-review-scraper#2]
I see everything is set on my computer, but I don't understand the how to run this.
How do I use the example code given ?
Thank you.

**Comment by YasogaN** [comment]
This is a module which was made to run in a script. it cannot be run independently. 

The below imports the module in your script
```
import { scraper } from "google-maps-review-scraper"
```

Next you have to fetch the reviews
```
const reviews = await scraper("url", "sort_type", "search_query")
```
+ The `url` should look like the sample URL from: [the docs](https://github.com/YasogaN/google-maps-review-scraper/blob/main/docs/urls/place.md)
+ The `sort_type` should be `"relevent"`, `"newest"`, `"highest_rating"` or `"lowest_rating"` depending on how you want the results sorted. 
+ The `search_query` is an optional paremeter you can include if you want the results to return something specifc. For example: I can include the word `tourist` to get all reviews with the word `tourist`.

**Comment by Bharat0112** [comment]
Hi, 
Can you provide a sample script if possible ?
Thank you.

**Comment by YasogaN** [comment]
#### Setting Up

1. Using your favourite package manager, install the module
```console
npm i google-maps-review-scraper
```
or 
```console
yarn add google-maps-review-scraper
```


2. The following code will get reviews about the Washignton Monument with the keyword tourist and write it to `reviews.json`
```js
import { scraper } from "google-maps-review-scraper"
import fs from 'fs';

const reviews = await scraper("https://www.google.com/maps/place/Washington+Monument/@38.8883683,-77.0386836,16.17z/data=!4m6!3m5!1s0x89b7b7a1be0c2e7f:0xe97346828ed0bfb8!8m2!3d38.8894838!4d-77.0352791!16zL20vMDE2ZGZm", "relevent", "tourist")

fs.writeFile('reviews.json', JSON.stringify(reviews, null, 2), (err) => {
    if (err) {
        console.error('Error writing to file', err);
    } else {
        console.log('Reviews successfully written to reviews.json');
    }
});
```

My file is saved as test.js so i run:
```console
node test.js
```


The output of reviews.json would include reviews on the Washignton Monument and has the word `tourist` in the review.

I am unable to provide the format it returns the json in, but I will be adding documentation on it within a couple days.

If you have any more questions or need further assistance, please don't hesitate to ask!

**Comment by YasogaN** [comment]
TODO:

- [ ] Add documentation for the json output

**Comment by YasogaN** [comment]
Happy to hear that your issue is solved. Currently, there is no way to control the number of results, but it will be added in a future release.

**Comment by YasogaN** [comment]
@Bharat0112 Please update to v1.2 to have page control features. Documentation has been added to the docs folder.

**Comment by Bharat0112** [comment]
That was fast. Thank you very much.

**Comment by YasogaN** [comment]
Hi,
Just wanted to know, does it keep scraping beyond 35 pages? It would return 350 arrays inside the main array if it was 35 pages. I am already aware that the created json file will be huge (around 1k and 1.5k lines per result). It is raw output from google maps `listugcposts` endpoint without any processing, as some users might need.

However, your suggestion is great. It would be a good enhancement, but would be very time consuming and tiresome. Currently, I do not have enough time in my hands to implement this, but i will get around to it within a couple weeks. I will be creating a seperate issue for the suggestion.

**Comment by Bharat0112** [comment]
Hi,
I don't know how google map counts pages, but I put 3 as 'pages' string in your above example, and it scraped 36 pages in total. But I have no idea how many reviews exactly are there, due to json structure.
I am not into huge scraping or anything, so this works for now.
Thank you very much.

**Comment by YasogaN** [comment]
Hi, is there any chance you can provide me with the JSON file? This seems to be an issue with the code as there should only be `30`  results within the main JSON file and should not equal to 300K lines.

**Comment by Bharat0112** [comment]
I extracted reviews using regex, and there are 100 reviews in total.
I've attached the file.
[reviews.zip](https://github.com/user-attachments/files/17187811/reviews.zip)

**Comment by doublenine99** [comment]
> I extracted reviews using regex, and there are 100 reviews in total. I've attached the file.

Can you share the regex you are using to extract the reviews from json?
