### ISSUE TITLE
[ENHANCEMENT] Cleaned output

### ISSUE THREAD

**Issue by YasogaN** [YasogaN/google-maps-review-scraper#3]
> Just a suggestion that only if it scrapes necessary data such as date, name, reviews etc. because it created json file with more than 3,00,000 lines for around 35 pages.

_Originally posted by @Bharat0112 in https://github.com/YasogaN/google-maps-review-scraper/issues/2#issuecomment-2381439962_

**Comment by YasogaN** [comment]
> However, your suggestion is great. It would be a good enhancement, but would be very time consuming and tiresome. Currently, I do not have enough time in my hands to implement this, but i will get around to it within a couple weeks. I will be creating a seperate issue for the suggestion.

*Originally posted by @YasogaN in [#2 (comment)](https://github.com/YasogaN/google-maps-review-scraper/issues/2#issuecomment-2381660478)*

**Comment by YasogaN** [comment]
@SnoozeThis wait for 2 weeks -> assign to YasogaN@, remind me

**Comment by SnoozeThis** [comment]
Sorry, I don't understand "remind me"

**Comment by SnoozeThis** [comment]
Sorry, I don't understand "remind me"

**Comment by YasogaN** [comment]
@SnoozeThis wait for 2 weeks -> assign to YasogaN@, tell "Reminder"

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/ZX12b6qHqOY) I will wait until Mon, 14 Oct 2024 00:28:45 UTC and then assign to @YasogaN and mention Reminder.

**Comment by SnoozeThis** [comment]
Resolved.

@Reminder
